remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: [Predicting power-Outage Durations]
tagline: [This site presents my DSC 80 Project 4 analysis of the U.S.&nbsp;major power‑outages dataset.]
